name: 'GT deploy action'
description: 'This Action will deploy a GT service built on dockerhub to ecs cluster'
author: Gutenberg Technology
branding:
  icon: 'arrow-up-right'  
  color: 'blue'
inputs:
  cluster_name:
    description: 'ECS cluster name'
    required: true
  services:
    description: 'list of services separated by space. Ex: gateway user dictionary'
    required: true
  env:
    description: 'target env: rct, preprod, prod'
    required: true
    default: rct
  ref:
    description: 'git reference to deploy: master, v1.2.0, ...'
    required: true
    default: master
  aws_access_key_id:
    description: 'AWS access key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS secret access key'
    required: true
  working_folder:
    description: 'Where to run gtd'
    required: true
runs:
  using: "composite"
  steps: 
    - id: print-available-values
      run: echo ${{ inputs.cluster_name }} secret:${{ inputs.aws_access_key_id }} ${{ github.action_path }} working_folder:${{ inputs.working_folder }} 
      shell: bash
    - run: echo "Super"
      shell: bash
    - id: download-gtd
      run: curl -L https://github.com/Gutenberg-Technology/gtd/releases/download/v0.2.2a/gtd -o gtd
      shell: bash
      working-directory: ${{ inputs.working_folder }}
    - run: ls ${{ inputs.working_folder }}/
      shell: bash
    - id: try-gtd
      run: gtd help
      shell: bash
      working-directory: ${{ inputs.working_folder }}

